
title: "William Benton"
tagline: ""
description: "Follow <a href=\"https://micro.blog/willb\">@willb on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/willb\">@willb on Micro.blog</a>."
baseurl: ""
url: "http://mu.willb.io"
markdown: "kramdown"
username: "willb"
microblog_user: "willb"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "William Benton"
name: "William Benton"
gravatar_hash: "473c4fbc4fd2478baf8fb0665c44a573"
avatar: "https://micro.blog/willb/avatar.jpg"
full_name: "William Benton"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"
site_id: "4803"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "William Benton"